-- MySQL Script generated by MySQL Workbench
-- Sun 04 Dec 2016 03:13:01 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_users
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_users` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_users` ;

-- -----------------------------------------------------
-- Table `ulbora_users`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_users`.`customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip` VARCHAR(5) NOT NULL,
  `email` VARCHAR(150) NULL,
  `created_date` DATETIME NOT NULL,
  `last_updated` DATETIME NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_users`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_users`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_users`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_users`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `activation_code` VARCHAR(150) NULL,
  `created_date` DATETIME NOT NULL,
  `last_updated` DATETIME NULL,
  `email` VARCHAR(150) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `role_id` BIGINT NOT NULL,
  `customer_id` BIGINT NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  INDEX `fk_user_customer1_idx` (`customer_id` ASC),
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ulbora_users`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ulbora_users`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
